version: '3.8'

#DATABASE
services:
  mongo_db:
    image: mongo:4.4.27
    container_name: 'mongo_db'
    restart: always
    ports:
      - '27017:27017'
    networks:
      - custom
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=strava
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  #STRAVA BOT
  strava:
    container_name: 'strava'
    image: strava:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - MONGO_URI=mongodb://mongo_db/
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - custom
    depends_on:
      - mongo_db
    restart: unless-stopped

  webhook:
    build: .
    command: uvicorn webhook:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
      - strava
    restart: always

networks:
  custom:
    driver: bridge

volumes:
  mongodb_data: